load("//tools/bazel:graphql.bzl", "graphql_codegen")

graphql_codegen(
    name = "graphql_codegen",
    srcs = [
        "//projects/organizer/task/src/main/resources/schema",
        "//projects/organizer/tasklist:codegen",
        "//projects/organizer/tasklist:gql",
    ],
    visibility = ["//projects/organizer/tasklist:__pkg__"],
)
