load("//tools/bazel:java.bzl", "java_binary", "java_library")

java_library(
    name = "main_lib",
    resources = [
        "//projects/wide/service/src/main/resources/schema",
    ] + glob(["resources/**"]),
    visibility = ["//projects/wide/service/src/test:__subpackages__"],
    runtime_deps = [
        "//projects/wide/service/src/main/java/lab/wide",
        "//projects/wide/service/src/main/java/lab/wide/config",
        "@maven//:com_netflix_graphql_dgs_dgs_starter",
        "@maven//:org_flywaydb_flyway_database_postgresql",
        "@maven//:org_postgresql_postgresql",
        "@maven//:org_springframework_ai_spring_ai_starter_mcp_server_webmvc",
        "@maven//:org_springframework_boot_spring_boot_starter_actuator",
        "@maven//:org_springframework_boot_spring_boot_starter_data_jdbc",
        "@maven//:org_springframework_boot_spring_boot_starter_flyway",
        "@maven//:org_springframework_boot_spring_boot_starter_web",
    ],
)

java_binary(
    name = "main",
    env = {"SPRING_PROFILES_ACTIVE": "local"},
    main_class = "lab.wide.WideApplication",
    visibility = [
        "//projects/wide:__pkg__",
        "//projects/wide/service:__pkg__",
    ],
    runtime_deps = [":main_lib"],
)
