load("//tools/bazel:java.bzl", "java_test_suite")

java_test_suite(
    name = "application",
    srcs = ["TaskEventHandlerTest.java"],
    runner = "junit5",
    runtime_deps = [
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_reporting",
    ],
    deps = [
        "//libs/test/src/test/java/lab/test:test-test-lib",
        "//projects/organizer/autojournal/src/main/java/lab/autojournal/application",
        "@maven//:org_assertj_assertj_core",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_mockito_mockito_core",
        "@maven//:org_mockito_mockito_junit_jupiter",
    ],
)
