query AllLineItems {
  allLineItems {
    id
    name
    categorizations {
      categoryId
      categoryValueId
    }
  }
  allCategories {
    id
    name
    values {
      id
      name
    }
  }
}
