server.port: ${ORGANIZER_AUTOJOURNAL_PORT:3002}
lab:
  services:
    task:
      graphql-url: http://localhost:${ORGANIZER_TASK_PORT:3001}/graphql
    journal:
      graphql-url: http://localhost:${ORGANIZER_JOURNAL_PORT:3003}/graphql
spring:
  kafka:
    bootstrap-servers: localhost:${ORGANIZER_KAFKA_PORT:9092}
    properties:
      schema.registry.url: http://localhost:${ORGANIZER_SCHEMA_REGISTRY_PORT:8081}
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
      properties:
        derive.type: true
