CREATE TABLE IF NOT EXISTS LINE_ITEM (
  ID UUID PRIMARY KEY NOT NULL,
  VERSION INTEGER NOT NULL,
  NAME VARCHAR(256) NOT NULL
);

CREATE TABLE IF NOT EXISTS CATEGORY (
  ID UUID PRIMARY KEY NOT NULL,
  VERSION INTEGER NOT NULL,
  NAME VARCHAR(256) NOT NULL
);

CREATE TABLE IF NOT EXISTS CATEGORY_VALUE (
  ID UUID PRIMARY KEY NOT NULL,
  CATEGORY UUID NOT NULL,
  NAME VARCHAR(256) NOT NULL
);

CREATE TABLE IF NOT EXISTS CATEGORIZATION (
    LINE_ITEM UUID NOT NULL,
    CATEGORY_ID UUID NOT NULL,
    CATEGORY_VALUE_ID UUID NOT NULL
);
