load("//tools/bazel:java.bzl", "java_test_suite")

java_test_suite(
    name = "kafka",
    timeout = "moderate",
    srcs = [
        "EmbeddedKafkaIntegrationTest.java",
        "KafkaApplicationTest.java",
    ],
    runner = "junit5",
    tags = ["requires-network"],
    runtime_deps = [
        "//learn/kafka/src/test/resources",
        "@maven//:io_confluent_kafka_protobuf_serializer",
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_reporting",
        "@maven//:org_springframework_boot_spring_boot_starter_test",
    ],
    deps = [
        "//learn/kafka/src/main/java/lab/learn/kafka",
        "//learn/kafka/src/main/proto:kafka_java",
        "@maven//:org_assertj_assertj_core",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_mockito_mockito_core",
        "@maven//:org_springframework_boot_spring_boot_test",
        "@maven//:org_springframework_kafka_spring_kafka",
        "@maven//:org_springframework_kafka_spring_kafka_test",
        "@maven//:org_springframework_spring_beans",
        "@maven//:org_springframework_spring_test",
    ],
)
