CREATE TABLE CHAT_OUTBOX (
  CHAT_ID UUID NOT NULL REFERENCES CHAT(ID) ON DELETE CASCADE,
  MESSAGE_ID UUID NOT NULL,
  TOOL_CALL_ID VARCHAR(256) NOT NULL DEFAULT '',
  ATTEMPTS INTEGER NOT NULL DEFAULT 0,
  AVAILABLE_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (CHAT_ID, MESSAGE_ID, TOOL_CALL_ID)
);

CREATE INDEX CHAT_OUTBOX_AVAILABLE ON CHAT_OUTBOX (AVAILABLE_AT, CREATED_AT);

-- Recover work that the former in-process listeners could have lost.
INSERT INTO CHAT_OUTBOX (CHAT_ID, MESSAGE_ID)
SELECT CHAT, ID FROM CHAT_MESSAGE WHERE TYPE = 'ASSISTANT' AND STATUS = 'PENDING';

INSERT INTO CHAT_OUTBOX (CHAT_ID, MESSAGE_ID, TOOL_CALL_ID)
SELECT M.CHAT, M.ID, T.ID
FROM TOOL_CALL T JOIN CHAT_MESSAGE M ON M.ID = T.CHAT_MESSAGE
WHERE M.STATUS = 'COMPLETED' AND T.STATUS = 'APPROVED' AND T.RESULT IS NULL;
