load("//tools/bazel:java.bzl", "java_test_suite")

java_test_suite(
    name = "task",
    timeout = "short",
    srcs = ["TaskApplicationTest.java"],
    resources = ["//projects/organizer/task/src/main/resources"],
    runner = "junit5",
    tags = ["requires-network"],
    runtime_deps = [
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_reporting",
        "@maven//:org_springframework_boot_spring_boot_starter_test",
    ],
    deps = [
        "//projects/organizer/task/src/main/java/lab/task",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_springframework_boot_spring_boot_test",
        "@maven//:org_springframework_kafka_spring_kafka_test",
    ],
)
