load("//tools/bazel:java.bzl", "java_library")

java_library(
    name = "config",
    srcs = [
        "AiConfig.java",
        "DatabaseConfig.java",
        "HttpClientConfig.java",
        "IdentityProperties.java",
        "SecurityConfig.java",
    ],
    visibility = [
        "//projects/mops/service/src/main:__pkg__",
        "//projects/mops/service/src/test/java/lab/mops/ai/infrastructure/outbox:__pkg__",
    ],
    exports = [
        "//libs/identity/src/main/java/lab/libs/identity",
        "@maven//:org_springframework_ai_spring_ai_model",
        "@maven//:org_springframework_boot_spring_boot_restclient",
        "@maven//:org_springframework_security_spring_security_oauth2_jose",
        "@maven//:org_springframework_security_spring_security_web",
    ],
    runtime_deps = [
        "//projects/mops/service/src/main/java/lab/mops/config/client",
        "@maven//:com_h2database_h2",
    ],
    deps = [
        "//libs/ddd/src/main/java/lab/libs/ddd/domain/springdata",
        "//libs/identity/src/main/java/lab/libs/identity",
        "//libs/identity/src/main/java/lab/libs/identity/jwt",
        "//libs/identity/src/main/java/lab/libs/identity/web",
        "//libs/spring/src/main/java/lab/spring/http",
        "//projects/mops/service/src/main/java/lab/mops/core/api/ai",
        "@maven//:org_springframework_ai_spring_ai_model",
        "@maven//:org_springframework_boot_spring_boot",
        "@maven//:org_springframework_boot_spring_boot_restclient",
        "@maven//:org_springframework_data_spring_data_jdbc",
        "@maven//:org_springframework_security_spring_security_config",
        "@maven//:org_springframework_security_spring_security_oauth2_jose",
        "@maven//:org_springframework_security_spring_security_oauth2_resource_server",
        "@maven//:org_springframework_security_spring_security_web",
        "@maven//:org_springframework_spring_context",
    ],
)
