load("//tools/bazel:java.bzl", "java_junit5_test")

java_junit5_test(
    name = "RedisTest",
    srcs = ["RedisTest.java"],
    tags = [
        "requires-docker",
        "requires-network",
    ],
    test_class = "lab.learn.testcontainers.redis.RedisTest",
    runtime_deps = [
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_reporting",
    ],
    deps = [
        "//libs/test/src/test/java/lab/test:test-test-lib",
        "@maven//:org_assertj_assertj_core",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_testcontainers_testcontainers",
        "@maven//:org_testcontainers_testcontainers_junit_jupiter",
        "@maven//:redis_clients_jedis",
    ],
)
