server.port: ${ORGANIZER_TASK_PORT:3001}
spring:
  graphql.graphiql.enabled: true
  kafka:
    bootstrap-servers: localhost:${ORGANIZER_KAFKA_PORT:9092}
    properties:
      schema.registry.url: http://localhost:${ORGANIZER_SCHEMA_REGISTRY_PORT:8081}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer
