CREATE TABLE IF NOT EXISTS BUDGET (
  ID UUID PRIMARY KEY NOT NULL,
  VERSION INTEGER NOT NULL,
  NAME VARCHAR(256) NOT NULL,
  CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS LINE_ITEM (
  ID UUID PRIMARY KEY NOT NULL,
  BUDGET_ID UUID NOT NULL,
  VERSION INTEGER NOT NULL,
  NAME VARCHAR(256) NOT NULL,
  CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CATEGORY (
  ID UUID PRIMARY KEY NOT NULL,
  VERSION INTEGER NOT NULL,
  NAME VARCHAR(256) NOT NULL,
  CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CATEGORY_VALUE (
  ID UUID PRIMARY KEY NOT NULL,
  CATEGORY UUID NOT NULL,
  NAME VARCHAR(256) NOT NULL
);

CREATE TABLE IF NOT EXISTS SPEND (
  LINE_ITEM UUID NOT NULL,
  SPEND_DAY DATE NOT NULL,
  AMOUNT DECIMAL(10,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS CATEGORIZATION (
    LINE_ITEM UUID NOT NULL,
    CATEGORY_ID UUID NOT NULL,
    CATEGORY_VALUE_ID UUID NOT NULL
);

CREATE TABLE IF NOT EXISTS ACTIVITY (
    ID UUID PRIMARY KEY NOT NULL,
    VERSION INTEGER NOT NULL,
    NAME VARCHAR(256) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CHAT (
    ID UUID PRIMARY KEY NOT NULL,
    VERSION INTEGER NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CHAT_MESSAGE (
    ID UUID PRIMARY KEY NOT NULL,
    CHAT UUID NOT NULL,
    CHAT_KEY INTEGER NOT NULL,
    TYPE VARCHAR(256) NOT NULL,
    STATUS VARCHAR(256) NOT NULL,
    CONTENT TEXT,
    TIMESTAMP TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
