load("//tools/bazel:java.bzl", "java_test_suite")

java_test_suite(
    name = "tools",
    runner = "junit5",
    runtime_deps = [
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_reporting",
    ],
    deps = [
        "//libs/spring_ai_tools/src/main/java/lab/springai/tools",
        "//libs/test/src/test/java/lab/test",
        "@maven//:org_assertj_assertj_core",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_mockito_mockito_core",
        "@maven//:org_mockito_mockito_junit_jupiter",
        "@maven//:org_springframework_spring_context",
    ],
)
