load("//tools/bazel:java.bzl", "java_test_suite")

java_test_suite(
    name = "domain",
    srcs = [
        "AggregateTest.java",
        "BaseRepositoryTest.java",
        "EventSourcedAggregateTest.java",
        "ExternalIdTest.java",
        "InternalIdTest.java",
        "StringValueTest.java",
    ],
    runner = "junit5",
    runtime_deps = [
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_reporting",
    ],
    deps = [
        "//libs/ddd/src/main/java/lab/libs/ddd/domain",
        "//libs/ddd/src/test/java/lab/libs/ddd/domain/test:test-test-lib",
        "//libs/test/src/test/java/lab/test:test-test-lib",
        "@maven//:org_assertj_assertj_core",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_mockito_mockito_core",
    ],
)
