load("//tools/bazel:java.bzl", "java_library")

java_library(
    name = "testing",
    testonly = True,
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//libs/identity/src/main/java/lab/libs/identity/jwt",
        "@maven//:com_nimbusds_nimbus_jose_jwt",
    ],
)
