load("//tools/bazel:java.bzl", "java_test_suite")

java_test_suite(
    name = "kafka",
    runner = "junit5",
    tags = [
        "requires-docker",
        "requires-network",
    ],
    runtime_deps = [
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_reporting",
    ],
    deps = [
        "//libs/test/src/test/java/lab/test",
        "@maven//:org_apache_kafka_kafka_clients",
        "@maven//:org_assertj_assertj_core",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_mockito_mockito_core",
        "@maven//:org_mockito_mockito_junit_jupiter",
        "@maven//:org_testcontainers_testcontainers",
        "@maven//:org_testcontainers_testcontainers_junit_jupiter",
        "@maven//:org_testcontainers_testcontainers_kafka",
    ],
)
