load("//tools/bazel:java.bzl", "java_test_suite")

java_test_suite(
    name = "mops",
    srcs = ["MopsApplicationTest.java"],
    runner = "junit5",
    runtime_deps = [
        "//projects/mops/service/src/main:main_lib",
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_reporting",
        "@maven//:org_springframework_boot_spring_boot_starter_test",
    ],
    deps = [
        "//projects/mops/service/src/main/java/lab/mops",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_springframework_boot_spring_boot_test",
    ],
)
