load("//tools/bazel:graphql.bzl", "graphql_codegen")

graphql_codegen(
    name = "graphql_codegen",
    srcs = [
        "//projects/mops/app:codegen",
        "//projects/mops/app:gql",
        "//projects/mops/service/src/main/resources/schema",
    ],
    visibility = ["//projects/mops/app:__pkg__"],
)
