import type { Person } from "./Table";

export const data: Person[] = [
  {
    id: 1,
    firstName: "Wava",
    lastName: "Hoppe",
    address: "4456 Towne Estates",
    city: "Edmond",
    state: "California",
  },
  {
    id: 2,
    firstName: "Kamren",
    lastName: "Kemmer",
    address: "237 Reinger View",
    city: "Kesslermouth",
    state: "New Jersey",
  },
  {
    id: 3,
    firstName: "Dillon",
    lastName: "Hackett",
    address: "79266 Cronin Rest",
    city: "Conroyland",
    state: "Colorado",
  },
  {
    id: 4,
    firstName: "Wilber",
    lastName: "Von",
    address: "4162 Della Roads",
    city: "Champaign",
    state: "Idaho",
  },
  {
    id: 5,
    firstName: "Ronny",
    lastName: "Lowe",
    address: "4057 Burley Extensions",
    city: "Siennastead",
    state: "Alaska",
  },
  {
    id: 6,
    firstName: "Lavinia",
    lastName: "Kreiger",
    address: "24310 Aufderhar Union",
    city: "Ceceliachester",
    state: "Kentucky",
  },
  {
    id: 7,
    firstName: "Tracy",
    lastName: "Wilkinson",
    address: "7204 Claudine Summit",
    city: "Fort Melanychester",
    state: "Tennessee",
  },
];
