load("//tools/bazel:java.bzl", "java_test_suite")

java_test_suite(
    name = "budget",
    srcs = [
        "BudgetDataFetcherTest.java",
        "BudgetMapperTest.java",
        "BudgetMutationTest.java",
    ],
    runner = "junit5",
    runtime_deps = [
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_reporting",
    ],
    deps = [
        "//libs/test/src/test/java/lab/test:test-test-lib",
        "//projects/mops/service/src/main/java/lab/mops/common/api/gql",
        "//projects/mops/service/src/main/java/lab/mops/core/api/gql/budget",
        "//projects/mops/service/src/main/java/lab/mops/core/application/budget",
        "//projects/mops/service/src/main/java/lab/mops/core/domain/budget",
        "//projects/mops/service/src/main/resources/schema:java",
        "@maven//:jakarta_servlet_jakarta_servlet_api",
        "@maven//:org_assertj_assertj_core",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_mockito_mockito_core",
        "@maven//:org_mockito_mockito_junit_jupiter",
    ],
)
