load("//tools/bazel:graphql.bzl", "graphql_codegen")

graphql_codegen(
    name = "graphql_codegen",
    srcs = [
        "//projects/organizer/journal/src/main/resources/schema",
        "//projects/organizer/journal_app:codegen",
        "//projects/organizer/journal_app/src/entries:gql",
    ],
    visibility = ["//projects/organizer/journal_app:__subpackages__"],
)
