mutation AddUserMessage($input: AddUserMessageInput!) {
  addUserMessage(input: $input) {
    code
    success
    message
    chat {
      id
      messages {
        id
        type
        status
        content
        createdAt
        updatedAt
      }
      createdAt
      updatedAt
    }
  }
}
