load("//tools/bazel:java.bzl", "java_test_suite")

java_test_suite(
    name = "http",
    srcs = ["BufferedResponseReaderTest.java"],
    runner = "junit5",
    runtime_deps = [
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_reporting",
    ],
    deps = [
        "//libs/spring/src/main/java/lab/spring/http",
        "@maven//:org_assertj_assertj_core",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_mockito_mockito_core",
        "@maven//:org_springframework_spring_web",
    ],
)
