load("//tools/bazel:java.bzl", "java_library")

java_library(
    name = "chat",
    srcs = [
        "AssistantMessageRetriedEvent.java",
        "Chat.java",
        "ChatId.java",
        "ChatMessageAddedEvent.java",
        "ChatMessageCancelledEvent.java",
        "ChatMessageCompletedEvent.java",
        "ChatMessageEditedEvent.java",
        "ChatMessageFailedEvent.java",
        "ChatRepository.java",
        "ChatStartedEvent.java",
        "Message.java",
        "MessageId.java",
        "MessageStatus.java",
        "MessageType.java",
        "PendingAssistantMessageAddedEvent.java",
        "PendingToolCallsAddedEvent.java",
        "PendingToolsCompletedEvent.java",
        "ToolCall.java",
        "ToolCallApprovedEvent.java",
        "ToolCallId.java",
        "ToolCallRejectedEvent.java",
        "ToolCallStatus.java",
        "ToolExecutedEvent.java",
    ],
    visibility = [
        "//projects/mops/service/src:__subpackages__",
    ],
    deps = [
        "//libs/ddd/src/main/java/lab/libs/ddd/domain",
        "@maven//:org_springframework_data_spring_data_commons",
        "@maven//:org_springframework_data_spring_data_jdbc",
        "@maven//:org_springframework_data_spring_data_relational",
        "@maven//:org_springframework_spring_context",
    ],
)
