query AllLineItems {
  allLineItems {
    id
    name
    spending {
      day
      amount
    }
    categorizations {
      category {
        id
      }
      categoryValue {
        name
      }
    }
  }
}
