load("//tools/bazel:java.bzl", "java_library")

java_library(
    name = "jwt",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//libs/identity/src/main/java/lab/libs/identity",
        "@maven//:org_springframework_security_spring_security_core",
        "@maven//:org_springframework_security_spring_security_oauth2_core",
        "@maven//:org_springframework_security_spring_security_oauth2_jose",
        "@maven//:org_springframework_spring_core",
    ],
)
