load("@npm//:@playwright/test/package_json.bzl", playwright_bin = "bin")

playwright_bin.playwright_test(
    name = "e2e",
    size = "medium",
    args = [
        "test",
        "--config",
        "projects/organizer/e2e/playwright.config.ts",
    ],
    data = [
        "autojournal.spec.ts",
        "fixtures.ts",
        "playwright.config.ts",
        "routing.spec.ts",
        "runner.ts",
        "//:node_modules/@playwright/test",
        "//:node_modules/@testcontainers/kafka",
        "//:node_modules/@types/dockerode",
        "//:node_modules/dockerode",
        "//:node_modules/testcontainers",
        "//infra/local:router_conf",
        "//infra/local/proxy:tarball.tar",
        "//projects/organizer/autojournal/src/main:deliver.tar",
        "//projects/organizer/journal/src/main:deliver.tar",
        "//projects/organizer/journal_app:deliver.tar",
        "//projects/organizer/task/src/main:deliver.tar",
        "//projects/organizer/tasklist:deliver.tar",
        "@playwright//:chromium-headless-shell",
    ],
    env = {
        "DEBUG": "testcontainers*",
        "PLAYWRIGHT_BROWSERS_PATH": "$(rootpath @playwright//:chromium-headless-shell)/../",
    },
    tags = [
        "no-coverage",
        "requires-docker",
        "requires-network",
    ],
)
