load("@npm//:vitest/package_json.bzl", vitest_bin = "bin")
load("//tools/bazel:js.bzl", "js_library")

package(default_visibility = ["//visibility:public"])

vitest_bin.vitest_binary(
    name = "vitest_binary",
)

js_library(
    name = "vite_config",
    srcs = ["vite.config.ts"],
    deps = [
        ":test_config",
        "//:node_modules/jsdom",
    ],
)

js_library(
    name = "coverage_config",
    srcs = ["coverage.ts"],
    deps = ["//:node_modules/@vitest/coverage-v8"],
)

js_library(
    name = "package_json",
    srcs = ["package.json"],
)

js_library(
    name = "test_config",
    srcs = ["config.ts"],
    deps = [
        ":coverage_config",
        ":package_json",
        "//:node_modules/jsdom",
        "//:node_modules/vitest",
    ],
)
