load("//tools/bazel:fe.bzl", "fe_app")
load("//tools/bazel:js.bzl", "js_library")
load("//tools/bazel:pkg.bzl", "tar")
load("//tools/bazel/oci:defs.bzl", "oci_deliver", "oci_image")

js_library(
    name = "codegen",
    srcs = ["codegen.ts"],
    visibility = ["//projects/organizer/journal_app/src/__generated__:__pkg__"],
)

js_library(
    name = "gql",
    srcs = glob(["src/**/*.gql"]),
    visibility = ["//projects/organizer/journal_app/src/__generated__:__pkg__"],
)

SRC_PATTERNS = [
    "src/**/*.ts",
    "src/**/*.tsx",
]

TEST_PATTERNS = [
    "src/**/*.test.ts",
    "src/**/*.test.tsx",
    "src/**/*.spec.ts",
    "src/**/*.spec.tsx",
    "src/**/__tests__/**/*.ts",
    "src/**/__tests__/**/*.tsx",
    "src/**/__fixtures__/**/*.ts",
    "src/**/__fixtures__/**/*.tsx",
    "src/test/**/*.ts",
    "src/test/**/*.tsx",
]

STORY_PATTERNS = [
    "src/**/*.stories.ts",
    "src/**/*.stories.tsx",
]

fe_app(
    name = "app",
    srcs = glob(
        SRC_PATTERNS,
        exclude = TEST_PATTERNS + STORY_PATTERNS,
    ),
    data = [
        "index.html",
        "package.json",
        "public/vite.svg",
        "vite.config.ts",
        "//:node_modules/@vitejs/plugin-react",
        "//:node_modules/jsdom",
        "//:node_modules/vitest",
        "//tools/bazel/vitest:coverage_config",
    ],
    test_deps = ["//tools/bazel/vitest:utils"],
    test_srcs = glob(
        TEST_PATTERNS,
        allow_empty = True,
    ),
    deps = [
        "//:node_modules/@apollo/client",
        "//:node_modules/@lab/bubbles",
        "//:node_modules/@mantine/core",
        "//:node_modules/@types/react",
        "//:node_modules/@types/react-dom",
        "//:node_modules/react",
        "//:node_modules/react-dom",
        "//:node_modules/vite",
        "//projects/organizer/journal_app/src/__generated__:graphql_codegen_ts",
    ],
)

# Preserve the existing package-default development command.
alias(
    name = "journal_app",
    actual = ":app",
)

tar(
    name = "tar",
    srcs = [":build"],
    # The vite devserver needs to make requests to "base: /journal/" when behind the
    # proxy since the $http_referer can't be used to identify the right app to proxy to.
    # Keep aligned with:
    # - projects/organizer/journal_app/vite.config.ts: "base"
    # - infra/local/proxy/nginx.conf: "proxy_pass"
    package_dir = "/usr/share/nginx/html/journal",
    strip_prefix = "dist",
)

oci_image(
    name = "image",
    base = "@nginx_alpine_slim",
    tars = [":tar"],
)

oci_deliver(
    name = "deliver",
    image = ":image",
    repo_suffix = "journal-app",
    visibility = [
        "//projects/organizer:__pkg__",
        "//projects/organizer/e2e:__pkg__",
    ],
)
