load("//tools/bazel:java.bzl", "SPRING_TEST_DEPS", "SPRING_TEST_RUNTIME_DEPS", "java_test_suite")

java_test_suite(
    name = "identity",
    runtime_deps = SPRING_TEST_RUNTIME_DEPS + [
        "//projects/mops/service/src/main:main_lib",
    ],
    deps = SPRING_TEST_DEPS + [
        "//libs/identity/src/main/java/lab/libs/identity/web",
        "@maven//:org_springframework_boot_spring_boot_webmvc_test",
        "@maven//:org_springframework_spring_web",
    ],
)
