load("//tools/bazel:java.bzl", "java_library")

java_library(
    name = "springdata",
    srcs = [
        "Converters.java",
        "ExternalIdToStringConverter.java",
        "InternalIdToUUIDConverter.java",
        "StringToExternalIdConverter.java",
        "StringToExternalIdConverterFactory.java",
        "StringToStringValueConverter.java",
        "StringToStringValueConverterFactory.java",
        "StringValueToStringConverter.java",
        "UUIDToInternalIdConverter.java",
        "UUIDToInternalIdConverterFactory.java",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//libs/ddd/src/main/java/lab/libs/ddd/domain",
        "@maven//:org_springframework_data_spring_data_commons",
        "@maven//:org_springframework_spring_core",
    ],
)
