name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  common_ci:
    runs-on: ubuntu-latest
    env:
      BAZELISK_HOME: ~/.cache/bazel-home
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup-java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Cache bazel on successful builds
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.BAZELISK_HOME }}
            ~/.cache/bazel
          key: bazel-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            bazel-${{ github.ref }}-
            bazel-

      - name: Build with bazel
        run: bazel build //...

      - name: Test with bazel
        run: bazel test //...

  pull_request_ci:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup python
        uses: actions/setup-python@v3

      - name: Check format, linting and style
        uses: pre-commit/action@v3.0.0
