name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cache bazelisk and bazel outputs
        uses: actions/cache@v2.1.7
        env:
          cache-name: bazel-cache
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel
          key: ${{ runner.os }}-${{ env.cache-name }}
      
      - uses: actions/checkout@v2
      
      - name: Build with bazel
        run: bazel build //...
      
      - name: Test with bazel
        run: bazel test //...
