name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cache bazel on successful builds
        uses: actions/cache@v2.1.7
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel
          key: bazel-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            bazel-${{ github.ref }}-
            bazel-

      - uses: actions/checkout@v2
      
      - name: Build with bazel
        run: bazel build //...
      
      - name: Test with bazel
        run: bazel test //...
