name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  common_ci:
    runs-on: ubuntu-latest
    env:
      BAZELISK_HOME: ~/.cache/bazel-home
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache bazel on successful builds
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.BAZELISK_HOME }}
            ~/.cache/bazel
          key: bazel-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            bazel-${{ github.ref }}-
            bazel-

      - name: Build with bazel
        run: bazel build //...

      - name: Test with bazel
        run: bazel test //...

  pull_request_ci:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Check format
        run: pnpm check-format

      - name: Check linting
        run: pnpm check-lint

      - name: Fetch head ref
        run: git fetch origin ${{ github.head_ref }}

      - name: Check commit message
        run: git show -s --format=%B origin/${{ github.head_ref }} | pnpm commitlint
